### ISSUE TITLE
Incompatible type for getting or setting field at Oracle CLOB

### ISSUE THREAD

**Issue by akardapolov** [Carbonado/Carbonado#5]
Error stack trace here:

```
Exception in thread "AWT-EventQueue-0" java.lang.VerifyError: (class: org/rtv/model/database/remote/entity/SqlOracle$132, method: load signature: (Lcom/amazon/carbonado/repo/jdbc/JDBCConnectionCapability;)Ljava/sql/Clob;) Incompatible type for getting or setting field at org.rtv.model.database.remote.entity.SqlOracle$3.extractData$(com.amazon.carbonado.repo.jdbc.JDBCStorableGenerator)
    at org.rtv.model.database.remote.entity.SqlOracle$3.extractAll$(com.amazon.carbonado.repo.jdbc.JDBCStorableGenerator)
    at org.rtv.model.database.remote.entity.SqlOracle$3.<init>(com.amazon.carbonado.repo.jdbc.JDBCStorableGenerator)
    at org.rtv.model.database.remote.entity.SqlOracle$3$205.instantiate(org.cojen.util.QuickConstructorGenerator)
    at com.amazon.carbonado.repo.jdbc.JDBCStorage.instantiate(JDBCStorage.java:358)
    at com.amazon.carbonado.repo.jdbc.JDBCCursor.next(JDBCCursor.java:109)
    at com.amazon.carbonado.repo.jdbc.JDBCCursor.next(JDBCCursor.java:38)
    at org.rtv.model.database.LocalRemoteDBManager.selectAndLoadVSQLDataToLocalBDB(LocalRemoteDBManager.java:74)
```

```

selectAndLoadVSQLDataToLocalBDB.java
...
       Storage<SqlBDB> storageLocal = this.localDBManager.getStorageVSQLBDB();
        try {
            Query queryRemote = getRemoteQueryVSQL(sqlid);
            Cursor<SqlOracle> cursorRemote = queryRemote.fetch();
            while (cursorRemote.hasNext()) {
                /* Query data from remote Oracle database */
                SqlOracle sr = cursorRemote.next(); <---- Line 74 here ----->
                /* Load data to local DBD storage */
                SqlBDB sl = storageLocal.prepare();
                /* Populate data */
                populateAll(sr,sl);
                try {
                    sl.insert();
                } catch (PersistException e) {
                    getLog().info("UniqueConstraintException at insert data to local BDB: " + sr);
                }
            }
        } catch (FetchException e) {
            getLog().error(e);
        } catch (Exception e) {
            getLog().error(e);
        }
..
```

```
Code from org/rtv/model/database/remote/entity/SqlOracle.java that causes the error
...
    @Nullable
    @Alias("SQL_FULLTEXT")
    Clob getSqlFulltext();
    void setSqlFulltext(Clob sqlFulltext);
...
```

Everything working well except getting/setting CLOB data values.

Thanks,
Alex.

**Comment by broneill** [comment]
Run your test with this java option: -Dorg.cojen.classfile.RuntimeClassFile.DEBUG=true

All the generated code will be written to the temp directory, and a message is written to standard for each one.

The "org/rtv/model/database/remote/entity/SqlOracle$132" class is the interesting one, although the number chosen is random each time. So you need to check the verify error to see what the exact name is. The generated code should be a class which implements the JDBCClobLoader interface.

You can disassemble the class using any tool you like, or use the one from Cojen:

cd <temp>/org/rtv/model/database/remote/entity
java org.cojen.classfile.DisassemblyTool SqlOracle$132

**Comment by jesterpm** [comment]
Closing due to inactivity.
